### PR TITLE
Add Merkle Tree extension

### PR DESCRIPTION
**Pull request by jonhealy1**
Add Merkle Tree extension information to the README

### CODE REVIEW

**Comment by jonhealy1** [comment]
@m-mohr Hi. Who can I bug about getting this looked at?

**Review by m-mohr — CHANGES_REQUESTED** [review]
You need to add the repo here:
https://github.com/stac-extensions/stac-extensions.github.io/blob/main/python/config.py
The README is updated automatically and should not be changed.

**Comment by jonhealy1** [comment]
@m-mohr Thanks for the help. Sorry about not reading the readme carefully enough.

**Comment by m-mohr** [comment]
If you've used the extension template, the extension should go into COMMUNITY_REPOS

**Comment by jonhealy1** [comment]
@m-mohr thanks makes sense

**Pull request merged**
